import { type NextRequest, NextResponse } from 'next/server'
import { getInternalSession } from '@/lib/auth/get-session'

// Server-side proxy: browser hits /api/ahs/<path> with no API key in
// headers or body; we forward to AHS_BASE_URL/ahs/<path> with X-API-Key
// injected from server-side env. Defense-in-depth: also require a valid
// session cookie before forwarding.

// COUCH_* names take precedence; bare names are a fallback. See lib/ahs.ts.
const AHS_BASE_URL = (
  process.env.COUCH_AHS_BASE_URL ?? process.env.AHS_BASE_URL ?? 'http://localhost:8090'
).replace(/\/$/, '')
const AHS_API_KEY = process.env.COUCH_AHS_API_KEY ?? process.env.AHS_API_KEY ?? ''

// Headers we strip before forwarding to AHS. host/connection are managed
// by undici/node-fetch; X-API-Key is set by us; content-length/encoding
// are regenerated by fetch from the body.
const HOP_BY_HOP = new Set([
  'host',
  'connection',
  'content-length',
  'transfer-encoding',
  'x-api-key',
  'cookie',
])

async function proxy(req: NextRequest, segments: string[]): Promise<Response> {
  const session = await getInternalSession()
  if (session.status !== 'authenticated') {
    return NextResponse.json({ detail: 'unauthenticated' }, { status: 401 })
  }

  const path = segments.map(encodeURIComponent).join('/')
  const url = new URL(`${AHS_BASE_URL}/ahs/${path}`)
  for (const [k, v] of req.nextUrl.searchParams.entries()) {
    url.searchParams.set(k, v)
  }

  const headers: Record<string, string> = {}
  req.headers.forEach((value, key) => {
    if (!HOP_BY_HOP.has(key.toLowerCase())) {
      headers[key] = value
    }
  })
  headers['X-API-Key'] = AHS_API_KEY

  const init: RequestInit & { duplex?: 'half' } = {
    method: req.method,
    headers,
    cache: 'no-store',
    redirect: 'manual',
  }

  if (req.method !== 'GET' && req.method !== 'HEAD') {
    init.body = await req.arrayBuffer()
  }

  const upstream = await fetch(url, init)

  // Copy response, stripping hop-by-hop headers.
  const respHeaders = new Headers()
  upstream.headers.forEach((value, key) => {
    if (!HOP_BY_HOP.has(key.toLowerCase())) {
      respHeaders.set(key, value)
    }
  })

  return new Response(upstream.body, {
    status: upstream.status,
    statusText: upstream.statusText,
    headers: respHeaders,
  })
}

type Ctx = { params: Promise<{ path: string[] }> }

export async function GET(req: NextRequest, ctx: Ctx) {
  const { path } = await ctx.params
  return proxy(req, path)
}
export async function POST(req: NextRequest, ctx: Ctx) {
  const { path } = await ctx.params
  return proxy(req, path)
}
export async function PUT(req: NextRequest, ctx: Ctx) {
  const { path } = await ctx.params
  return proxy(req, path)
}
export async function PATCH(req: NextRequest, ctx: Ctx) {
  const { path } = await ctx.params
  return proxy(req, path)
}
export async function DELETE(req: NextRequest, ctx: Ctx) {
  const { path } = await ctx.params
  return proxy(req, path)
}
