"""add user type

Revision ID: 72b8fc67c047
Revises: bd88e050d33f
Create Date: 2026-03-30 08:40:56.746224+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '72b8fc67c047'
down_revision: str | None = 'bd88e050d33f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_type', sa.Enum('HUMAN', 'AGENT', name='usertype'), server_default='HUMAN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    # ### end Alembic commands ###
