"""add slugs to artifacts

Revision ID: 79205821473e
Revises: 37ba95f14212
Create Date: 2026-04-14 21:41:12.968507+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '79205821473e'
down_revision: str | None = '37ba95f14212'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_artifacts', sa.Column('named_slug', sa.Text(), nullable=True))
    op.add_column('agent_artifacts', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('agent_artifacts', sa.Column('content_type', sa.Text(), nullable=True))
    op.create_index('uix_agent_artifacts_slug_version', 'agent_artifacts', ['named_slug', 'version'], unique=True, postgresql_where=sa.text('named_slug IS NOT NULL AND version IS NOT NULL'))
    op.create_check_constraint(
        'ck_agent_artifacts_content_type',
        'agent_artifacts',
        "content_type IN ('text/plain', 'text/markdown', 'text/html')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_agent_artifacts_content_type', 'agent_artifacts', type_='check')
    op.drop_index('uix_agent_artifacts_slug_version', table_name='agent_artifacts', postgresql_where=sa.text('named_slug IS NOT NULL AND version IS NOT NULL'))
    op.drop_column('agent_artifacts', 'content_type')
    op.drop_column('agent_artifacts', 'version')
    op.drop_column('agent_artifacts', 'named_slug')
    # ### end Alembic commands ###
