"""users: add identity-mapping columns (slack_user_id, github_username, linear_name)

Revision ID: 4cb43319077c
Revises: 044d3d3336c8
Create Date: 2026-04-21 18:10:02.194544+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4cb43319077c'
down_revision: str | None = '044d3d3336c8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('slack_user_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('github_username', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('linear_name', sa.Text(), nullable=True))
    op.create_index('idx_users_github_username_unique', 'users', ['github_username'], unique=True, postgresql_where=sa.text('github_username IS NOT NULL'))
    op.create_index('idx_users_slack_user_id_unique', 'users', ['slack_user_id'], unique=True, postgresql_where=sa.text('slack_user_id IS NOT NULL'))
    op.create_index(op.f('ix_users_github_username'), 'users', ['github_username'], unique=False)
    op.create_index(op.f('ix_users_linear_name'), 'users', ['linear_name'], unique=False)
    op.create_index(op.f('ix_users_slack_user_id'), 'users', ['slack_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_slack_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_linear_name'), table_name='users')
    op.drop_index(op.f('ix_users_github_username'), table_name='users')
    op.drop_index('idx_users_slack_user_id_unique', table_name='users', postgresql_where=sa.text('slack_user_id IS NOT NULL'))
    op.drop_index('idx_users_github_username_unique', table_name='users', postgresql_where=sa.text('github_username IS NOT NULL'))
    op.drop_column('users', 'linear_name')
    op.drop_column('users', 'github_username')
    op.drop_column('users', 'slack_user_id')
    # ### end Alembic commands ###
