"""Add AgentMessage model and A2A enums

Revision ID: 37ba95f14212
Revises: 04308c50cf51
Create Date: 2026-04-04 05:41:47.609894+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "37ba95f14212"
down_revision: str | None = "04308c50cf51"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new values to existing enums.
    # Must commit before referencing new values in CHECK constraints (PG requirement).
    op.execute(sa.text("COMMIT"))
    op.execute(sa.text("ALTER TYPE agentsessiontrigger ADD VALUE IF NOT EXISTS 'AGENT'"))
    op.execute(sa.text("ALTER TYPE agentsessionmessagerole ADD VALUE IF NOT EXISTS 'FELLOW_AGENT'"))
    op.execute(sa.text("BEGIN"))

    op.create_table(
        "agent_messages",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=True),
        sa.Column("modified_at", sa.DateTime(timezone=True), server_default=sa.text("(now())"), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("agent_message_id", sa.Uuid(), nullable=False),
        sa.Column("from_agent_id", sa.Uuid(), nullable=False),
        sa.Column("to_agent_id", sa.Uuid(), nullable=False),
        sa.Column("from_session_id", sa.Uuid(), nullable=True),
        sa.Column("to_session_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("message_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status", sa.Enum("QUEUED", "DELIVERING", "DELIVERED", "FAILED", name="agentmessagestatus"), nullable=False
        ),
        sa.Column("queued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("resolved_session_id", sa.Uuid(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint("attempt_count <= max_attempts", name="ck_agent_message_attempt_count"),
        sa.ForeignKeyConstraint(
            ["from_agent_id"], ["agents.agent_id"], name=op.f("fk_agent_messages_from_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["from_session_id"],
            ["agent_sessions.agent_session_id"],
            name=op.f("fk_agent_messages_from_session_id_agent_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["resolved_session_id"],
            ["agent_sessions.agent_session_id"],
            name=op.f("fk_agent_messages_resolved_session_id_agent_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["to_agent_id"], ["agents.agent_id"], name=op.f("fk_agent_messages_to_agent_id_agents")
        ),
        sa.ForeignKeyConstraint(
            ["to_session_id"],
            ["agent_sessions.agent_session_id"],
            name=op.f("fk_agent_messages_to_session_id_agent_sessions"),
        ),
        sa.PrimaryKeyConstraint("agent_message_id", name=op.f("pk_agent_messages")),
    )
    op.create_index("ix_agent_message_from_session", "agent_messages", ["from_session_id"], unique=False)
    op.create_index(
        "ix_agent_message_stale_delivering",
        "agent_messages",
        ["claimed_at"],
        unique=False,
        postgresql_where=sa.text("status = 'DELIVERING'"),
    )
    op.create_index(
        "ix_agent_message_to_agent_queued",
        "agent_messages",
        ["to_agent_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'QUEUED' AND to_session_id IS NULL"),
    )
    op.create_index(
        "ix_agent_message_to_session_queued",
        "agent_messages",
        ["to_session_id", "status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('QUEUED', 'DELIVERING') AND to_session_id IS NOT NULL"),
    )
    op.create_index(op.f("ix_agent_messages_from_agent_id"), "agent_messages", ["from_agent_id"], unique=False)
    op.create_index(op.f("ix_agent_messages_to_agent_id"), "agent_messages", ["to_agent_id"], unique=False)
    op.add_column("agent_session_messages", sa.Column("from_agent_id", sa.Uuid(), nullable=True))
    op.add_column("agent_session_messages", sa.Column("agent_message_id_ref", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_agent_session_messages_agent_message_id_ref"),
        "agent_session_messages",
        ["agent_message_id_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_session_messages_from_agent_id"), "agent_session_messages", ["from_agent_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_agent_session_messages_agent_message_id_ref_agent_messages"),
        "agent_session_messages",
        "agent_messages",
        ["agent_message_id_ref"],
        ["agent_message_id"],
    )
    op.create_foreign_key(
        op.f("fk_agent_session_messages_from_agent_id_agents"),
        "agent_session_messages",
        "agents",
        ["from_agent_id"],
        ["agent_id"],
    )
    op.create_check_constraint(
        "ck_agent_session_message_fellow_agent_provenance",
        "agent_session_messages",
        "(role = 'FELLOW_AGENT') = (from_agent_id IS NOT NULL)",
    )
    op.add_column("agents", sa.Column("agent_user_id", sa.Text(), nullable=True))
    op.create_index(op.f("ix_agents_agent_user_id"), "agents", ["agent_user_id"], unique=False)
    op.create_foreign_key(op.f("fk_agents_agent_user_id_users"), "agents", "users", ["agent_user_id"], ["user_id"])
    # ### end Alembic commands ###

    # ------------------------------------------------------------------
    # Data backfill: create a user row for every existing agent so that
    # the new agent_user_id FK can be populated.  Safe to re-run because
    # the INSERT uses ON CONFLICT DO NOTHING.
    # ------------------------------------------------------------------
    op.execute(
        sa.text(
            """
            INSERT INTO users (user_id, name, email, user_type, status)
            SELECT
                agent_id::text,
                'agent:' || name,
                'agent-' || name || '@yupp.ai',
                'AGENT',
                'ACTIVE'
            FROM agents
            WHERE NOT EXISTS (
                SELECT 1 FROM users WHERE user_id = agents.agent_id::text
            )
            ON CONFLICT DO NOTHING
            """
        )
    )
    # Populate agent_user_id for any agent not yet linked to a user row.
    op.execute(sa.text("UPDATE agents SET agent_user_id = agent_id::text WHERE agent_user_id IS NULL"))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_agents_agent_user_id_users"), "agents", type_="foreignkey")
    op.drop_index(op.f("ix_agents_agent_user_id"), table_name="agents")
    op.drop_column("agents", "agent_user_id")
    op.drop_constraint("ck_agent_session_message_fellow_agent_provenance", "agent_session_messages", type_="check")
    op.drop_constraint(
        op.f("fk_agent_session_messages_from_agent_id_agents"), "agent_session_messages", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_agent_session_messages_agent_message_id_ref_agent_messages"),
        "agent_session_messages",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_agent_session_messages_from_agent_id"), table_name="agent_session_messages")
    op.drop_index(op.f("ix_agent_session_messages_agent_message_id_ref"), table_name="agent_session_messages")
    op.drop_column("agent_session_messages", "agent_message_id_ref")
    op.drop_column("agent_session_messages", "from_agent_id")
    op.drop_index(op.f("ix_agent_messages_to_agent_id"), table_name="agent_messages")
    op.drop_index(op.f("ix_agent_messages_from_agent_id"), table_name="agent_messages")
    op.drop_index(
        "ix_agent_message_to_session_queued",
        table_name="agent_messages",
        postgresql_where=sa.text("status IN ('QUEUED', 'DELIVERING') AND to_session_id IS NOT NULL"),
    )
    op.drop_index(
        "ix_agent_message_to_agent_queued",
        table_name="agent_messages",
        postgresql_where=sa.text("status = 'QUEUED' AND to_session_id IS NULL"),
    )
    op.drop_index(
        "ix_agent_message_stale_delivering",
        table_name="agent_messages",
        postgresql_where=sa.text("status = 'DELIVERING'"),
    )
    op.drop_index("ix_agent_message_from_session", table_name="agent_messages")
    op.drop_table("agent_messages")

    # Drop the enum type (not auto-dropped by drop_table)
    sa.Enum(name="agentmessagestatus").drop(op.get_bind(), checkfirst=True)

    # Note: Cannot remove values from PostgreSQL enums — AGENT and FELLOW_AGENT
    # values remain in agentsessiontrigger and agentsessionmessagerole.
    # ### end Alembic commands ###
