"""baseline schema

Revision ID: bd88e050d33f
Revises: 
Create Date: 2026-03-30 08:17:52.956312+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd88e050d33f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('agents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('executor_type', sa.Enum('HARNESSED', 'RAW', name='agentexecutortype'), server_default='HARNESSED', nullable=False),
    sa.Column('executor_model', sa.Text(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creator_user_id', sa.Text(), nullable=True),
    sa.Column('additional_system_prompt', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_creator_user_id'), 'agents', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=True)
    op.create_table('mcp_dev_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mcp_dev_token_id', sa.Uuid(), nullable=False),
    sa.Column('token_lookup_key', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='mcptokenstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('revoked_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('mcp_dev_token_id', name=op.f('pk_mcp_dev_tokens'))
    )
    op.create_index(op.f('ix_mcp_dev_tokens_email'), 'mcp_dev_tokens', ['email'], unique=False)
    op.create_index('ix_mcp_dev_tokens_email_status', 'mcp_dev_tokens', ['email', 'status'], unique=False)
    op.create_index(op.f('ix_mcp_dev_tokens_token_hash'), 'mcp_dev_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_mcp_dev_tokens_token_lookup_key'), 'mcp_dev_tokens', ['token_lookup_key'], unique=False)
    op.create_table('roles',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Enum('ADMIN', 'READONLY', 'ADMIN_AGENT', 'ENGINEER', 'YUPPASTE_USER', 'MCP_USER', name='role_name_enum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name='uq_roles_name'),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('slack_agents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('slack_agent_id', sa.Uuid(), nullable=False),
    sa.Column('app_id', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('bot_name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', 'PENDING_APPROVAL', name='slackagentstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('created_by_user_id', sa.Text(), nullable=True),
    sa.Column('bot_creation_request_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('slack_agent_id', name=op.f('pk_slack_agents'))
    )
    op.create_index(op.f('ix_slack_agents_agent_name'), 'slack_agents', ['agent_name'], unique=False)
    op.create_index(op.f('ix_slack_agents_app_id'), 'slack_agents', ['app_id'], unique=True)
    op.create_index(op.f('ix_slack_agents_bot_name'), 'slack_agents', ['bot_name'], unique=False)
    op.create_table('slack_oauth_tokens',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_id', sa.Uuid(), nullable=False),
    sa.Column('token_type', sa.Enum('BOT_FATHER_APP_CONFIG', name='slackoauthtokentype'), nullable=False),
    sa.Column('encrypted_refresh_token', sa.Text(), nullable=False),
    sa.Column('encrypted_access_token', sa.Text(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('token_id', name=op.f('pk_slack_oauth_tokens'))
    )
    op.create_index(op.f('ix_slack_oauth_tokens_token_type'), 'slack_oauth_tokens', ['token_type'], unique=True)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DEACTIVATED', name='userstatus'), server_default='ACTIVE', nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='users_email_key')
    )
    op.create_index('idx_users_lower_email', 'users', [sa.literal_column('lower(email)')], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('yuppaste_comment_threads',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('yuppaste_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('paste_version', sa.Integer(), nullable=True),
    sa.Column('anchor_text', sa.Text(), nullable=False),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('anchor_start_line', sa.Integer(), nullable=True),
    sa.Column('anchor_end_line', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='commentthreadstatus'), server_default='OPEN', nullable=False),
    sa.PrimaryKeyConstraint('thread_id', name=op.f('pk_yuppaste_comment_threads'))
    )
    op.create_index(op.f('ix_yuppaste_comment_threads_slug'), 'yuppaste_comment_threads', ['slug'], unique=False)
    op.create_index(op.f('ix_yuppaste_comment_threads_yuppaste_id'), 'yuppaste_comment_threads', ['yuppaste_id'], unique=False)
    op.create_table('agent_memory_sections',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_memory_section_id', sa.Uuid(), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_tsvector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('source_generation', sa.BigInteger(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_memory_sections_agent_id_agents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('agent_memory_section_id', name=op.f('pk_agent_memory_sections')),
    sa.UniqueConstraint('topic', 'section_key', name='uq_agent_memory_sections_topic_section_key')
    )
    op.create_index('ix_agent_memory_sections_content_tsvector', 'agent_memory_sections', ['content_tsvector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_agent_memory_sections_topic'), 'agent_memory_sections', ['topic'], unique=False)
    op.create_index('ix_agent_memory_sections_topic_section_key_live', 'agent_memory_sections', ['topic', 'section_key'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('agent_projects',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='agentprojectstatus'), server_default='PAUSED', nullable=False),
    sa.Column('creator_user_id', sa.Text(), nullable=True),
    sa.Column('default_agent_id', sa.Uuid(), nullable=True),
    sa.Column('project_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('shared_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_usd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('budget_spent_usd', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('slack_channel', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['default_agent_id'], ['agents.agent_id'], name=op.f('fk_agent_projects_default_agent_id_agents')),
    sa.PrimaryKeyConstraint('agent_project_id', name=op.f('pk_agent_projects'))
    )
    op.create_index(op.f('ix_agent_projects_creator_user_id'), 'agent_projects', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_agent_projects_default_agent_id'), 'agent_projects', ['default_agent_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('parent_session_id', sa.Uuid(), nullable=True),
    sa.Column('creator_user_id', sa.Text(), nullable=True),
    sa.Column('slack_session_id', sa.Text(), nullable=True),
    sa.Column('trigger', sa.Enum('SLACK', 'WEBHOOK', 'CRON', 'API', 'TASK', name='agentsessiontrigger'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('workspace', sa.Text(), nullable=True),
    sa.Column('llm_session_id', sa.Text(), nullable=True),
    sa.Column('extra_dirs', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'STALE', name='agentsessionstatus'), server_default='ACTIVE', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_sessions_agent_id_agents')),
    sa.ForeignKeyConstraint(['parent_session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_sessions_parent_session_id_agent_sessions')),
    sa.PrimaryKeyConstraint('agent_session_id', name=op.f('pk_agent_sessions')),
    sa.UniqueConstraint('slack_session_id', name=op.f('uq_agent_sessions_slack_session_id'))
    )
    op.create_index(op.f('ix_agent_sessions_agent_id'), 'agent_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_creator_user_id'), 'agent_sessions', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_parent_session_id'), 'agent_sessions', ['parent_session_id'], unique=False)
    op.create_table('mcp_audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mcp_audit_log_id', sa.Uuid(), nullable=False),
    sa.Column('mcp_dev_token_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('callback_url', sa.Text(), nullable=True),
    sa.Column('token_type', sa.Enum('DEV_TOKEN', 'OAUTH', name='mcptokentype'), server_default='DEV_TOKEN', nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('tool_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', name='mcpauditlogstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mcp_dev_token_id'], ['mcp_dev_tokens.mcp_dev_token_id'], name=op.f('fk_mcp_audit_logs_mcp_dev_token_id_mcp_dev_tokens')),
    sa.PrimaryKeyConstraint('mcp_audit_log_id', name=op.f('pk_mcp_audit_logs'))
    )
    op.create_index('ix_mcp_audit_logs_created_at', 'mcp_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_email'), 'mcp_audit_logs', ['email'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_mcp_dev_token_id'), 'mcp_audit_logs', ['mcp_dev_token_id'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_status'), 'mcp_audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_audit_logs_tool_name'), 'mcp_audit_logs', ['tool_name'], unique=False)
    op.create_index('ix_mcp_audit_logs_tool_name_created_at', 'mcp_audit_logs', ['tool_name', 'created_at'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission', sa.Enum('READ_USERS', 'WRITE_USERS', 'MANAGE_RBAC', 'READ_YUPPASTE', 'WRITE_YUPPASTE', 'USE_MCP', 'MANAGE_AGENTS', 'MANAGE_AGENT_SCHEDULES', 'MANAGE_AGENT_PROJECTS', 'MANAGE_AGENT_SESSIONS', 'CREATE_AGENT', name='permission_enum'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission', name='pk_role_permission')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('fk_user_roles_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_user_roles_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name='pk_user_role')
    )
    op.create_table('yuppaste_comments',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('parent_comment_id', sa.Uuid(), nullable=True),
    sa.Column('author_email', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['yuppaste_comments.comment_id'], name=op.f('fk_yuppaste_comments_parent_comment_id_yuppaste_comments')),
    sa.ForeignKeyConstraint(['thread_id'], ['yuppaste_comment_threads.thread_id'], name=op.f('fk_yuppaste_comments_thread_id_yuppaste_comment_threads')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('pk_yuppaste_comments'))
    )
    op.create_index(op.f('ix_yuppaste_comments_author_email'), 'yuppaste_comments', ['author_email'], unique=False)
    op.create_index(op.f('ix_yuppaste_comments_thread_id'), 'yuppaste_comments', ['thread_id'], unique=False)
    op.create_table('agent_memory_section_embeddings',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_memory_section_embedding_id', sa.Uuid(), nullable=False),
    sa.Column('agent_memory_section_id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('embedding_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['agent_memory_section_id'], ['agent_memory_sections.agent_memory_section_id'], name=op.f('fk_agent_memory_section_embeddings_agent_memory_section_id_agent_memory_sections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_memory_section_embedding_id', name=op.f('pk_agent_memory_section_embeddings')),
    sa.UniqueConstraint('agent_memory_section_id', 'embedding_model_name', name='uq_agent_memory_section_embeddings_section_model')
    )
    op.create_index(op.f('ix_agent_memory_section_embeddings_agent_memory_section_id'), 'agent_memory_section_embeddings', ['agent_memory_section_id'], unique=False)
    op.create_index('ix_agent_memory_section_embeddings_model_name', 'agent_memory_section_embeddings', ['embedding_model_name'], unique=False)
    op.create_table('agent_schedules',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_type', sa.Enum('SCHEDULED', 'RECURRING', name='agentscheduletype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', name='agentschedulestatus'), server_default='PENDING', nullable=False),
    sa.Column('execute_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron_expression', sa.Text(), nullable=True),
    sa.Column('cron_timezone', sa.Text(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('last_session_id', sa.Uuid(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_user', sa.Text(), nullable=False),
    sa.Column('created_by_agent', sa.Text(), nullable=True),
    sa.CheckConstraint("(schedule_type = 'SCHEDULED' AND execute_at IS NOT NULL) OR (schedule_type = 'RECURRING' AND cron_expression IS NOT NULL)", name=op.f('ck_agent_schedules_agent_schedules_type_fields_required')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_schedules_agent_id_agents')),
    sa.ForeignKeyConstraint(['last_session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_schedules_last_session_id_agent_sessions')),
    sa.PrimaryKeyConstraint('agent_schedule_id', name=op.f('pk_agent_schedules'))
    )
    op.create_index(op.f('ix_agent_schedules_agent_id'), 'agent_schedules', ['agent_id'], unique=False)
    op.create_index('ix_agent_schedules_status_next_run', 'agent_schedules', ['status', 'next_run_at'], unique=False)
    op.create_table('agent_security_incidents',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('agent_session_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.Enum('SECRETS_PROBE', 'MEMORY_MANIPULATION', 'SCOPE_MANIPULATION', 'SOCIAL_ENGINEERING', name='agentsecurityincidenttype'), nullable=False),
    sa.Column('severity', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='agentsecurityseverity'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('offense_number', sa.Integer(), nullable=False),
    sa.Column('auto_detected', sa.Boolean(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Text(), nullable=True),
    sa.Column('resolution', sa.Enum('FALSE_POSITIVE', 'CONFIRMED', 'MITIGATED', name='agentsecurityresolution'), nullable=True),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_security_incidents_agent_session_id_agent_sessions')),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_agent_security_incidents'))
    )
    op.create_index('ix_agent_security_incidents_reported_at', 'agent_security_incidents', ['reported_at'], unique=False)
    op.create_index('ix_agent_security_incidents_session', 'agent_security_incidents', ['agent_session_id'], unique=False)
    op.create_index('ix_agent_security_incidents_type_severity', 'agent_security_incidents', ['incident_type', 'severity'], unique=False)
    op.create_index('ix_agent_security_incidents_unreviewed', 'agent_security_incidents', ['reviewed_at'], unique=False, postgresql_where=sa.text('reviewed_at IS NULL'))
    op.create_table('agent_session_messages',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_session_message_id', sa.Uuid(), nullable=False),
    sa.Column('agent_session_id', sa.Uuid(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'AGENT', 'SYSTEM', name='agentsessionmessagerole'), nullable=False),
    sa.Column('creator_user_id', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('raw_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_name', sa.Text(), nullable=True),
    sa.Column('llm_message_id', sa.Text(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('num_agent_turns', sa.Integer(), nullable=True),
    sa.Column('slack_ts', sa.Text(), nullable=True),
    sa.Column('ttfct_ms', sa.Integer(), nullable=True),
    sa.Column('ttlct_ms', sa.Integer(), nullable=True),
    sa.Column('completion_status', sa.Enum('IN_PROGRESS', 'SUCCESS', 'FAILED', 'ABORTED', name='agentsessionmessagecompletionstatus'), server_default='SUCCESS', nullable=False),
    sa.Column('error_type', sa.Enum('NONE', 'ERROR_MAX_TURNS', 'ERROR_CONTEXT_OVERFLOW', 'ERROR_EXECUTOR', 'ERROR_INTERNAL', name='agentsessionmessageerrortype'), server_default='NONE', nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_session_messages_agent_session_id_agent_sessions')),
    sa.PrimaryKeyConstraint('agent_session_message_id', name=op.f('pk_agent_session_messages'))
    )
    op.create_index(op.f('ix_agent_session_messages_agent_session_id'), 'agent_session_messages', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_session_messages_creator_user_id'), 'agent_session_messages', ['creator_user_id'], unique=False)
    op.create_index('ix_agent_session_messages_session_turn', 'agent_session_messages', ['agent_session_id', 'turn_number'], unique=False)
    op.create_table('agent_tasks',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_task_id', sa.Uuid(), nullable=False),
    sa.Column('agent_project_id', sa.Uuid(), nullable=False),
    sa.Column('parent_task_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BLOCKED', 'READY', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', 'IN_REVIEW', name='agenttaskstatus'), server_default='PENDING', nullable=False),
    sa.Column('priority', sa.Enum('URGENT', 'HIGH', 'NORMAL', 'LOW', name='agenttaskpriority'), server_default='NORMAL', nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_session_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('task_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estimated_effort', sa.Text(), nullable=True),
    sa.Column('actual_spending_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('parent_task_id != agent_task_id', name=op.f('ck_agent_tasks_no_self_parent')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], name=op.f('fk_agent_tasks_agent_id_agents')),
    sa.ForeignKeyConstraint(['agent_project_id'], ['agent_projects.agent_project_id'], name=op.f('fk_agent_tasks_agent_project_id_agent_projects')),
    sa.ForeignKeyConstraint(['parent_task_id'], ['agent_tasks.agent_task_id'], name=op.f('fk_agent_tasks_parent_task_id_agent_tasks')),
    sa.PrimaryKeyConstraint('agent_task_id', name=op.f('pk_agent_tasks'))
    )
    op.create_index(op.f('ix_agent_tasks_agent_id'), 'agent_tasks', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_agent_project_id'), 'agent_tasks', ['agent_project_id'], unique=False)
    op.create_index(op.f('ix_agent_tasks_parent_task_id'), 'agent_tasks', ['parent_task_id'], unique=False)
    op.create_index('ix_agent_tasks_project_status', 'agent_tasks', ['agent_project_id', 'status'], unique=False)
    op.create_table('agent_artifacts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('YUPPASTE', 'CODE_REVIEW', 'OTHER', name='agentartifacttype'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('creator_user_id', sa.Text(), nullable=True),
    sa.Column('creator_agent_id', sa.Uuid(), nullable=True),
    sa.Column('agent_session_id', sa.Uuid(), nullable=True),
    sa.Column('agent_task_id', sa.Uuid(), nullable=True),
    sa.Column('artifact_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_artifacts_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['agent_task_id'], ['agent_tasks.agent_task_id'], name=op.f('fk_agent_artifacts_agent_task_id_agent_tasks')),
    sa.ForeignKeyConstraint(['creator_agent_id'], ['agents.agent_id'], name=op.f('fk_agent_artifacts_creator_agent_id_agents')),
    sa.PrimaryKeyConstraint('agent_artifact_id', name=op.f('pk_agent_artifacts'))
    )
    op.create_index(op.f('ix_agent_artifacts_agent_task_id'), 'agent_artifacts', ['agent_task_id'], unique=False)
    op.create_index(op.f('ix_agent_artifacts_creator_agent_id'), 'agent_artifacts', ['creator_agent_id'], unique=False)
    op.create_index(op.f('ix_agent_artifacts_creator_user_id'), 'agent_artifacts', ['creator_user_id'], unique=False)
    op.create_index('ix_agent_artifacts_session_type', 'agent_artifacts', ['agent_session_id', 'artifact_type'], unique=False)
    op.create_index('ix_agent_artifacts_type', 'agent_artifacts', ['artifact_type'], unique=False)
    op.create_table('agent_feedbacks',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_feedback_id', sa.Uuid(), nullable=False),
    sa.Column('agent_session_id', sa.Uuid(), nullable=False),
    sa.Column('agent_session_message_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('rating', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='agentfeedbackrating'), nullable=True),
    sa.Column('structured', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('slack_ts', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_feedbacks_agent_session_id_agent_sessions')),
    sa.ForeignKeyConstraint(['agent_session_message_id'], ['agent_session_messages.agent_session_message_id'], name=op.f('fk_agent_feedbacks_agent_session_message_id_agent_session_messages')),
    sa.PrimaryKeyConstraint('agent_feedback_id', name=op.f('pk_agent_feedbacks'))
    )
    op.create_index(op.f('ix_agent_feedbacks_agent_session_id'), 'agent_feedbacks', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_agent_feedbacks_agent_session_message_id'), 'agent_feedbacks', ['agent_session_message_id'], unique=False)
    op.create_index(op.f('ix_agent_feedbacks_user_id'), 'agent_feedbacks', ['user_id'], unique=False)
    op.create_table('agent_schedule_runs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('(now())'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_schedule_run_id', sa.Uuid(), nullable=False),
    sa.Column('agent_schedule_id', sa.Uuid(), nullable=False),
    sa.Column('run_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='agentschedulerunstatus'), server_default='PENDING', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_schedule_id'], ['agent_schedules.agent_schedule_id'], name=op.f('fk_agent_schedule_runs_agent_schedule_id_agent_schedules')),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.agent_session_id'], name=op.f('fk_agent_schedule_runs_session_id_agent_sessions')),
    sa.PrimaryKeyConstraint('agent_schedule_run_id', name=op.f('pk_agent_schedule_runs'))
    )
    op.create_index(op.f('ix_agent_schedule_runs_agent_schedule_id'), 'agent_schedule_runs', ['agent_schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_schedule_runs_agent_schedule_id'), table_name='agent_schedule_runs')
    op.drop_table('agent_schedule_runs')
    op.drop_index(op.f('ix_agent_feedbacks_user_id'), table_name='agent_feedbacks')
    op.drop_index(op.f('ix_agent_feedbacks_agent_session_message_id'), table_name='agent_feedbacks')
    op.drop_index(op.f('ix_agent_feedbacks_agent_session_id'), table_name='agent_feedbacks')
    op.drop_table('agent_feedbacks')
    op.drop_index('ix_agent_artifacts_type', table_name='agent_artifacts')
    op.drop_index('ix_agent_artifacts_session_type', table_name='agent_artifacts')
    op.drop_index(op.f('ix_agent_artifacts_creator_user_id'), table_name='agent_artifacts')
    op.drop_index(op.f('ix_agent_artifacts_creator_agent_id'), table_name='agent_artifacts')
    op.drop_index(op.f('ix_agent_artifacts_agent_task_id'), table_name='agent_artifacts')
    op.drop_table('agent_artifacts')
    op.drop_index('ix_agent_tasks_project_status', table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_parent_task_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_project_id'), table_name='agent_tasks')
    op.drop_index(op.f('ix_agent_tasks_agent_id'), table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_index('ix_agent_session_messages_session_turn', table_name='agent_session_messages')
    op.drop_index(op.f('ix_agent_session_messages_creator_user_id'), table_name='agent_session_messages')
    op.drop_index(op.f('ix_agent_session_messages_agent_session_id'), table_name='agent_session_messages')
    op.drop_table('agent_session_messages')
    op.drop_index('ix_agent_security_incidents_unreviewed', table_name='agent_security_incidents', postgresql_where=sa.text('reviewed_at IS NULL'))
    op.drop_index('ix_agent_security_incidents_type_severity', table_name='agent_security_incidents')
    op.drop_index('ix_agent_security_incidents_session', table_name='agent_security_incidents')
    op.drop_index('ix_agent_security_incidents_reported_at', table_name='agent_security_incidents')
    op.drop_table('agent_security_incidents')
    op.drop_index('ix_agent_schedules_status_next_run', table_name='agent_schedules')
    op.drop_index(op.f('ix_agent_schedules_agent_id'), table_name='agent_schedules')
    op.drop_table('agent_schedules')
    op.drop_index('ix_agent_memory_section_embeddings_model_name', table_name='agent_memory_section_embeddings')
    op.drop_index(op.f('ix_agent_memory_section_embeddings_agent_memory_section_id'), table_name='agent_memory_section_embeddings')
    op.drop_table('agent_memory_section_embeddings')
    op.drop_index(op.f('ix_yuppaste_comments_thread_id'), table_name='yuppaste_comments')
    op.drop_index(op.f('ix_yuppaste_comments_author_email'), table_name='yuppaste_comments')
    op.drop_table('yuppaste_comments')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_index('ix_mcp_audit_logs_tool_name_created_at', table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_tool_name'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_status'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_mcp_dev_token_id'), table_name='mcp_audit_logs')
    op.drop_index(op.f('ix_mcp_audit_logs_email'), table_name='mcp_audit_logs')
    op.drop_index('ix_mcp_audit_logs_created_at', table_name='mcp_audit_logs')
    op.drop_table('mcp_audit_logs')
    op.drop_index(op.f('ix_agent_sessions_parent_session_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_creator_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_agent_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_projects_default_agent_id'), table_name='agent_projects')
    op.drop_index(op.f('ix_agent_projects_creator_user_id'), table_name='agent_projects')
    op.drop_table('agent_projects')
    op.drop_index('ix_agent_memory_sections_topic_section_key_live', table_name='agent_memory_sections', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_agent_memory_sections_topic'), table_name='agent_memory_sections')
    op.drop_index('ix_agent_memory_sections_content_tsvector', table_name='agent_memory_sections', postgresql_using='gin')
    op.drop_table('agent_memory_sections')
    op.drop_index(op.f('ix_yuppaste_comment_threads_yuppaste_id'), table_name='yuppaste_comment_threads')
    op.drop_index(op.f('ix_yuppaste_comment_threads_slug'), table_name='yuppaste_comment_threads')
    op.drop_table('yuppaste_comment_threads')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_lower_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_slack_oauth_tokens_token_type'), table_name='slack_oauth_tokens')
    op.drop_table('slack_oauth_tokens')
    op.drop_index(op.f('ix_slack_agents_bot_name'), table_name='slack_agents')
    op.drop_index(op.f('ix_slack_agents_app_id'), table_name='slack_agents')
    op.drop_index(op.f('ix_slack_agents_agent_name'), table_name='slack_agents')
    op.drop_table('slack_agents')
    op.drop_table('roles')
    op.drop_index(op.f('ix_mcp_dev_tokens_token_lookup_key'), table_name='mcp_dev_tokens')
    op.drop_index(op.f('ix_mcp_dev_tokens_token_hash'), table_name='mcp_dev_tokens')
    op.drop_index('ix_mcp_dev_tokens_email_status', table_name='mcp_dev_tokens')
    op.drop_index(op.f('ix_mcp_dev_tokens_email'), table_name='mcp_dev_tokens')
    op.drop_table('mcp_dev_tokens')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_creator_user_id'), table_name='agents')
    op.drop_table('agents')
    # Drop all enum types created in upgrade
    for enum_name in [
        'agentartifacttype', 'agentexecutortype', 'agentfeedbackrating',
        'agentprojectstatus', 'agentschedulerunstatus', 'agentschedulestatus',
        'agentscheduletype', 'agentsecurityincidenttype', 'agentsecurityresolution',
        'agentsecurityseverity', 'agentsessionmessagecompletionstatus',
        'agentsessionmessageerrortype', 'agentsessionmessagerole',
        'agentsessionstatus', 'agentsessiontrigger', 'agenttaskpriority',
        'agenttaskstatus', 'commentthreadstatus', 'mcpauditlogstatus',
        'mcptokenstatus', 'mcptokentype', 'permission_enum', 'role_name_enum',
        'slackagentstatus', 'slackoauthtokentype', 'userstatus',
        'agentfeedbackrating',
    ]:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    op.execute('DROP EXTENSION IF EXISTS vector')
    # ### end Alembic commands ###
