"""slack_agents: add encrypted bot_token and signing_secret columns

Revision ID: 044d3d3336c8
Revises: 79205821473e
Create Date: 2026-04-21 17:15:27.117092+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '044d3d3336c8'
down_revision: str | None = '79205821473e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slack_agents', sa.Column('bot_token_encrypted', sa.Text(), nullable=True))
    op.add_column('slack_agents', sa.Column('signing_secret_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slack_agents', 'signing_secret_encrypted')
    op.drop_column('slack_agents', 'bot_token_encrypted')
    # ### end Alembic commands ###
