"""add user type

Revision ID: ab0aa44ff305
Revises: bd88e050d33f
Create Date: 2026-03-30 08:43:03.769139+00:00

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ab0aa44ff305'
down_revision: str | None = 'bd88e050d33f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    usertype = sa.Enum('HUMAN', 'AGENT', name='usertype')
    usertype.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('user_type', usertype, server_default='HUMAN', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_type')
    sa.Enum(name='usertype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
