#!/usr/bin/env python3
"""Generate a .env file for a VM-based service by fetching secrets from GCP Secret Manager.

Unlike Cloud Run services (which use --set-secrets to resolve secrets at runtime),
VM-based services need actual secret values written to a .env file on disk.

Usage:
    python generate_vm_env_file.py <environment> <service-name> <output-file>

This script:
1. Loads non-secret env vars from data/env_vars/ (base + environment + service configs)
2. Loads the secret mapping from data/secret-env-var-map.yml for the given service
3. Fetches each secret value from GCP Secret Manager
4. Writes everything to the output file in KEY=value format
"""

import sys
from typing import cast, get_args

from google.cloud import secretmanager
from scripts.generate_deploy_env import Environment, Service, load_config
from scripts.secret_env_var_map import validate_and_load_secret_env_var_map

GCP_PROJECT_ID = "yupp-llms"


def fetch_secret_value(client: secretmanager.SecretManagerServiceClient, secret_name: str, version: str) -> str:
    """Fetch a secret value from GCP Secret Manager."""
    name = f"projects/{GCP_PROJECT_ID}/secrets/{secret_name}/versions/{version}"
    response = client.access_secret_version(request={"name": name})
    return response.payload.data.decode("UTF-8")


def main() -> None:
    if len(sys.argv) != 4:
        print("Usage: generate_vm_env_file.py <environment> <service-name> <output-file>")
        sys.exit(1)

    environment = sys.argv[1]
    service_name = sys.argv[2]
    output_file = sys.argv[3]

    assert environment in ["staging", "production"], (
        f"<environment> {environment} must be one of 'staging', 'production'"
    )
    assert service_name in get_args(Service), f"<service_name> {service_name} must be one of {get_args(Service)}"

    env = cast(Environment, environment)
    service = cast(Service, service_name)

    # 1. Load non-secret env vars
    config = load_config(env, service)

    # 2. Load secret mapping
    secret_env_var_map = validate_and_load_secret_env_var_map()

    # 3. Fetch secrets from GCP Secret Manager
    client = secretmanager.SecretManagerServiceClient()
    secrets: dict[str, str] = {}
    failures: list[str] = []

    for env_var in secret_env_var_map.env_vars:
        if service not in env_var.services:
            continue
        if env not in env_var.secret_names:
            continue

        secret_name = env_var.secret_names[env]
        try:
            value = fetch_secret_value(client, secret_name, env_var.version)
            secrets[env_var.name] = value
        except Exception as e:
            failures.append(env_var.name)
            print(f"ERROR: Failed to fetch secret {env_var.name} ({secret_name}): {e}", file=sys.stderr)

    if failures:
        print(f"FATAL: {len(failures)} secret(s) failed to fetch: {failures}", file=sys.stderr)
        sys.exit(1)

    # 4. Write .env file — non-secret config first, then secrets
    with open(output_file, "w") as f:
        f.write("# Auto-generated by deploy workflow. Do not edit manually.\n")
        f.write(f"# Service: {service_name}, Environment: {environment}\n\n")

        f.write("# --- Non-secret configuration ---\n")
        for key, value in sorted(config.items()):
            escaped = str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            f.write(f'{key}="{escaped}"\n')

        f.write("\n# --- Secrets ---\n")
        for key, value in sorted(secrets.items()):
            escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            f.write(f'{key}="{escaped}"\n')

    print(f"Generated {output_file} with {len(config)} config vars and {len(secrets)} secrets.")


if __name__ == "__main__":
    main()
