"""User management CLI for the Yupp Agent Platform.

Assumes ``.env`` has been generated by ``python -m ypl.mono_server.setup``.
Reads database credentials via the standard Settings mechanism (POSTGRES_CONNECTION_AGENTDB).

Usage::

    python -m ypl.mono_server.manage add-user --email foo@bar.com --name "Foo Bar" --role ADMIN
    python -m ypl.mono_server.manage list-users [--limit 20]
    python -m ypl.mono_server.manage add-role --email foo@bar.com --role ENGINEER
    python -m ypl.mono_server.manage create-mcp-token --email foo@bar.com [--description "My token"]
    python -m ypl.mono_server.manage reset --yes
"""

from __future__ import annotations
import argparse
import asyncio
import sys
from typing import Any

from rich.console import Console
from rich.table import Table
from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine
from sqlmodel import select

import ypl.db.all_models  # noqa: F401 — register all SQLModel mappers
from ypl.db.rbac import Role, RoleName, UserRoleAssociation
from ypl.db.users import User, UserType
from ypl.mono_server.db import (
    create_mcp_dev_token,
    create_user_with_role,
    make_session_factory,
    seed_roles,
)

console = Console()


# ---------------------------------------------------------------------------
# Engine factory
# ---------------------------------------------------------------------------


def _get_async_engine() -> AsyncEngine:
    """Build an AsyncEngine from POSTGRES_CONNECTION_AGENTDB (via Settings).

    Raises:
        SystemExit: When POSTGRES_CONNECTION_AGENTDB is not configured.
    """
    try:
        from ypl.backend.config import settings

        url = settings.db_url(async_mode=True)
        return create_async_engine(url, pool_pre_ping=True)
    except Exception as exc:
        console.print(
            f"[red]✗ Cannot build database URL:[/red] {exc}\n"
            "Run [cyan]python -m ypl.mono_server.setup[/cyan] first to configure POSTGRES_CONNECTION_AGENTDB."
        )
        sys.exit(1)


# ---------------------------------------------------------------------------
# add-user
# ---------------------------------------------------------------------------


async def cmd_add_user(email: str, name: str, role: str | None) -> int:
    """Create a user, optionally assigning a role."""
    role_name: RoleName | None = None
    if role is not None:
        try:
            role_name = RoleName(role.upper())
        except ValueError:
            valid = ", ".join(r.value for r in RoleName)
            console.print(f"[red]Unknown role '{role}'.[/red]  Valid roles: {valid}")
            return 1

    engine = _get_async_engine()
    try:
        await create_user_with_role(
            engine,
            email=email,
            name=name,
            user_type=UserType.HUMAN,
            role_name=role_name,
        )
        console.print(f"[green]✓ User {email} created.[/green]")
        return 0
    except Exception as exc:
        console.print(f"[red]✗ Failed to create user:[/red] {exc}")
        return 1
    finally:
        await engine.dispose()


# ---------------------------------------------------------------------------
# list-users
# ---------------------------------------------------------------------------


async def cmd_list_users(limit: int = 20) -> int:
    """Print a table of users, most recently created first."""
    engine = _get_async_engine()
    try:
        factory = make_session_factory(engine)
        async with factory() as session:
            users = (
                await session.exec(
                    select(User).order_by(User.created_at.desc()).limit(limit)  # type: ignore[union-attr]
                )
            ).all()

        table = Table(title=f"Users (most recent {limit})", show_lines=True)
        table.add_column("email", style="cyan")
        table.add_column("name")
        table.add_column("type", style="dim")
        table.add_column("status", style="dim")
        table.add_column("created_at", style="dim")

        for u in users:
            created = str(u.created_at)[:19] if u.created_at else ""
            table.add_row(u.email, u.name or "", u.user_type.value, u.status.value, created)

        console.print(table)
        return 0
    except Exception as exc:
        console.print(f"[red]✗ Failed to list users:[/red] {exc}")
        return 1
    finally:
        await engine.dispose()


# ---------------------------------------------------------------------------
# add-role
# ---------------------------------------------------------------------------


async def cmd_add_role(email: str, role: str) -> int:
    """Assign a role to an existing user."""
    try:
        role_name = RoleName(role.upper())
    except ValueError:
        valid = ", ".join(r.value for r in RoleName)
        console.print(f"[red]Unknown role '{role}'.[/red]  Valid roles: {valid}")
        return 1

    engine = _get_async_engine()
    try:
        factory = make_session_factory(engine)
        async with factory() as session:
            user = (await session.exec(select(User).where(User.email == email.lower()))).first()
            if user is None:
                console.print(f"[red]User '{email}' not found.[/red]")
                return 1

            role_obj = (await session.exec(select(Role).where(Role.name == role_name))).first()
            if role_obj is None:
                console.print(
                    f"[red]Role {role_name.value} not found in database.[/red]  "
                    "Run [cyan]python -m ypl.mono_server.setup[/cyan] to seed roles."
                )
                return 1

            existing = (
                await session.exec(
                    select(UserRoleAssociation).where(
                        UserRoleAssociation.user_id == user.user_id,
                        UserRoleAssociation.role_id == role_obj.role_id,
                    )
                )
            ).first()
            if existing is not None:
                console.print(f"[dim]User {email} already has role {role_name.value} — no change.[/dim]")
                return 0

            session.add(UserRoleAssociation(user_id=user.user_id, role_id=role_obj.role_id))
            await session.commit()
            console.print(f"[green]✓ Role {role_name.value} assigned to {email}.[/green]")
            return 0
    except Exception as exc:
        console.print(f"[red]✗ Failed to assign role:[/red] {exc}")
        return 1
    finally:
        await engine.dispose()


# ---------------------------------------------------------------------------
# create-mcp-token
# ---------------------------------------------------------------------------


async def cmd_create_mcp_token(email: str, description: str) -> int:
    """Create an MCP developer token for the given user email."""
    engine = _get_async_engine()
    try:
        token = await create_mcp_dev_token(engine, email=email, description=description)
        from rich.panel import Panel

        console.print(
            Panel(
                f"[bold green]{token}[/bold green]\n\n"
                "[dim]Store this token securely — it cannot be retrieved later.\n"
                "Use it as a Bearer token when connecting to the MCP server.[/dim]",
                title=f"[bold]MCP Dev Token — {email}[/bold]",
                border_style="green",
            )
        )
        return 0
    except Exception as exc:
        console.print(f"[red]✗ Failed to create token:[/red] {exc}")
        return 1
    finally:
        await engine.dispose()


# ---------------------------------------------------------------------------
# reset
# ---------------------------------------------------------------------------


async def cmd_reset(yes: bool = False) -> int:
    """Re-seed roles and recreate the system user.

    This does NOT drop tables or delete existing human users.  It only ensures
    the standard roles exist and that system@yupp.ai is present.  Idempotent.
    """
    if not yes:
        from rich.prompt import Confirm

        if not Confirm.ask(
            "[yellow]This will re-seed roles and recreate system@yupp.ai.  Continue?[/yellow]",
            default=False,
        ):
            console.print("Aborted.")
            return 1

    engine = _get_async_engine()
    try:
        console.print("Seeding roles…")
        await seed_roles(engine)
        console.print("Recreating system user…")
        await create_user_with_role(
            engine,
            email="system@yupp.ai",
            name="System",
            user_type=UserType.SYSTEM,
            role_name=None,
        )
        console.print("[green]✓ Reset complete.[/green]")
        return 0
    except Exception as exc:
        console.print(f"[red]✗ Reset failed:[/red] {exc}")
        return 1
    finally:
        await engine.dispose()


# ---------------------------------------------------------------------------
# CLI argument parsing
# ---------------------------------------------------------------------------


def build_parser() -> argparse.ArgumentParser:
    """Build and return the top-level argument parser."""
    parser = argparse.ArgumentParser(
        prog="python -m ypl.mono_server.manage",
        description="User management CLI for the Yupp Agent Platform.",
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    # add-user
    p_add = sub.add_parser("add-user", help="Create a new user.")
    p_add.add_argument("--email", required=True, help="User email address.")
    p_add.add_argument("--name", required=True, help="Display name.")
    p_add.add_argument(
        "--role",
        default=None,
        help="Optional role to assign (ADMIN, ENGINEER, MCP_USER, …).",
    )

    # list-users
    p_list = sub.add_parser("list-users", help="List users.")
    p_list.add_argument("--limit", type=int, default=20, help="Maximum rows to show (default: 20).")

    # add-role
    p_role = sub.add_parser("add-role", help="Assign a role to an existing user.")
    p_role.add_argument("--email", required=True, help="User email address.")
    p_role.add_argument("--role", required=True, help="Role name (ADMIN, ENGINEER, MCP_USER, …).")

    # create-mcp-token
    p_token = sub.add_parser("create-mcp-token", help="Create an MCP developer token.")
    p_token.add_argument("--email", required=True, help="Email address to associate with the token.")
    p_token.add_argument("--description", default="Developer token", help="Token description.")

    # reset
    p_reset = sub.add_parser("reset", help="Re-seed roles and recreate the system user.")
    p_reset.add_argument(
        "--yes",
        action="store_true",
        default=False,
        help="Skip confirmation prompt.",
    )

    return parser


async def _run(args: Any) -> int:
    """Dispatch to the appropriate command handler."""
    if args.command == "add-user":
        return await cmd_add_user(args.email, args.name, args.role)
    if args.command == "list-users":
        return await cmd_list_users(args.limit)
    if args.command == "add-role":
        return await cmd_add_role(args.email, args.role)
    if args.command == "create-mcp-token":
        return await cmd_create_mcp_token(args.email, args.description)
    if args.command == "reset":
        return await cmd_reset(args.yes)

    build_parser().print_help()
    return 0


def main() -> None:
    """Entry point for ``python -m ypl.mono_server.manage``."""
    parser = build_parser()
    args = parser.parse_args()
    sys.exit(asyncio.run(_run(args)))


if __name__ == "__main__":
    main()
