"""External MCP registry + per-user OAuth/M2M grants.

The platform exposes a set of *external* MCP servers (Gmail, Google Drive,
Google Calendar, Linear, …) that agents can attach to, scoped to the
**human user** who originated the session.  This module declares the
DB schema; the FastAPI routes that drive OAuth + the Streamlit pages that
manage server entries + the resolver that injects servers into a session's
``.mcp.json`` live under :mod:`ypl.external_mcp` / :mod:`ypl.streamlit_server`.

Design overview
---------------

``mcp_servers``       — admin-registered external MCPs (slug, URL, auth_type,
                        oauth_config).  One row per external endpoint.
``mcp_server_secrets``— split sibling carrying Fernet-encrypted fields
                        (oauth_client_secret, m2m_shared_token) so default
                        reads of ``mcp_servers`` don't leak.
``mcp_server_roles``  — RBAC binding: which roles may *use* which server.
                        Avoids dynamic ``Permission`` enum values per slug.
``mcp_server_agents`` — which agents may *attach* which server (separately
                        from human-user access — an admin can scope a
                        powerful MCP to specific agents).
``mcp_user_grants``   — per-(user, server) authorization state: encrypted
                        access + refresh tokens for OBO, encrypted API key
                        for per-user M2M.
``mcp_grant_events``  — audit log: GRANTED / REFRESHED / REFRESH_FAILED /
                        USED / REVOKED.  Drives "MCP activity" view.

Encryption uses ``MCP_USER_GRANT_ENCRYPTION_KEY`` (Fernet, generated by the
Mac installer alongside the existing Slack/MCP keys).
"""

from __future__ import annotations
import enum
import uuid
from datetime import datetime

import sqlalchemy as sa
from sqlalchemy import Column, PrimaryKeyConstraint, Text, UniqueConstraint
from sqlalchemy import Enum as sa_Enum
from sqlalchemy.dialects import postgresql
from sqlmodel import Field, SQLModel

from ypl.db.base import BaseModel


class McpAuthType(str, enum.Enum):
    """How an external MCP authenticates inbound calls.

    OAUTH_OBO       — provider runs an OAuth 2.0 authorization-code flow.
                       Each user authorizes individually; we store their
                       access + refresh tokens and inject the bearer
                       header at session start.
    M2M_SHARED      — one bearer key configured by the admin, shared by
                       every authorized agent/user.  Coarse but cheap.
    M2M_PER_USER    — each user pastes their own bearer/API key.  Used
                       when the provider has no OAuth flow but still
                       wants per-user attribution.
    NONE            — provider is open (intranet, or auth handled by
                       network position).  Server URL is injected as-is.
    """

    OAUTH_OBO = "OAUTH_OBO"
    M2M_SHARED = "M2M_SHARED"
    M2M_PER_USER = "M2M_PER_USER"
    NONE = "NONE"


class McpTransport(str, enum.Enum):
    """MCP transport flavor on the wire."""

    STREAMABLE_HTTP = "STREAMABLE_HTTP"
    SSE = "SSE"


class McpGrantEventType(str, enum.Enum):
    """Audit-log event kinds for ``mcp_grant_events``."""

    GRANTED = "GRANTED"
    REFRESHED = "REFRESHED"
    REFRESH_FAILED = "REFRESH_FAILED"
    USED = "USED"
    REVOKED = "REVOKED"


class McpServer(BaseModel, table=True):
    """An external MCP endpoint that agents may attach to."""

    __tablename__ = "mcp_servers"

    mcp_server_id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True, nullable=False)
    slug: str = Field(sa_column=Column(Text, nullable=False, unique=True, index=True))
    display_name: str = Field(sa_type=Text, nullable=False)
    description: str | None = Field(default=None, sa_type=Text)
    url: str = Field(sa_type=Text, nullable=False)
    transport: McpTransport = Field(
        default=McpTransport.STREAMABLE_HTTP,
        sa_column=Column(sa_Enum(McpTransport, name="mcp_transport"), nullable=False),
    )
    auth_type: McpAuthType = Field(
        sa_column=Column(sa_Enum(McpAuthType, name="mcp_auth_type"), nullable=False),
    )
    # OAuth metadata, mirrored from the provider's docs.  Non-secret fields
    # only — client_id is here, client_secret is on ``mcp_server_secrets``.
    # Shape: {"client_id": str, "authorize_url": str, "token_url": str,
    #         "scopes": list[str], "extra_authorize_params": dict[str,str]}
    oauth_config: dict | None = Field(default=None, sa_column=Column(postgresql.JSONB, nullable=True))
    enabled: bool = Field(default=True, nullable=False)
    # If false, the resolver will refuse to write the bearer token to the
    # agent's ``.mcp.json``.  Phase-2 proxying lives here; for now any
    # admin enabling an MCP implicitly accepts the agent reading its token.
    allow_token_to_agent: bool = Field(default=True, nullable=False)

    __table_args__ = (UniqueConstraint("slug", name="uq_mcp_servers_slug"),)


class McpServerSecrets(SQLModel, table=True):
    """Sensitive fields kept in a separate table so ``SELECT * FROM mcp_servers``
    never leaks them.  All values are Fernet-encrypted with
    ``MCP_USER_GRANT_ENCRYPTION_KEY``.
    """

    __tablename__ = "mcp_server_secrets"

    mcp_server_id: uuid.UUID = Field(
        foreign_key="mcp_servers.mcp_server_id",
        primary_key=True,
        nullable=False,
    )
    oauth_client_secret_enc: str | None = Field(default=None, sa_type=Text)
    m2m_shared_token_enc: str | None = Field(default=None, sa_type=Text)


class McpServerRoleAccess(SQLModel, table=True):
    """Which roles may attach a given MCP.  Resolver intersects with the
    invoking user's roles before deciding to inject the server.

    Rationale for table-driven access (vs. Permission enum values per slug):
    we register MCPs dynamically at runtime, and the Permission enum can't
    grow without a schema migration.  This table lets admins add servers
    + grant access without code changes.
    """

    __tablename__ = "mcp_server_roles"

    mcp_server_id: uuid.UUID = Field(foreign_key="mcp_servers.mcp_server_id", nullable=False)
    role_id: uuid.UUID = Field(foreign_key="roles.role_id", nullable=False)

    __table_args__ = (PrimaryKeyConstraint("mcp_server_id", "role_id", name="pk_mcp_server_roles"),)


class McpServerAgent(SQLModel, table=True):
    """Which agents may attach a given MCP.  Lets admins keep e.g. Gmail
    attached only to a personal-assistant agent and not the code-reviewer.
    Empty agent list = available to every agent the user is allowed to invoke.
    """

    __tablename__ = "mcp_server_agents"

    mcp_server_id: uuid.UUID = Field(foreign_key="mcp_servers.mcp_server_id", nullable=False)
    agent_id: uuid.UUID = Field(foreign_key="agents.agent_id", nullable=False)

    __table_args__ = (PrimaryKeyConstraint("mcp_server_id", "agent_id", name="pk_mcp_server_agents"),)


class McpUserGrant(BaseModel, table=True):
    """Per-user authorization state for one external MCP.

    For OAUTH_OBO: ``access_token_enc`` + ``refresh_token_enc`` + ``expires_at``
    are populated; ``api_key_enc`` is null.

    For M2M_PER_USER: ``api_key_enc`` is populated; OAuth fields null.

    Soft-revoke via ``revoked_at``; a fresh grant is a brand-new row.
    """

    __tablename__ = "mcp_user_grants"

    grant_id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True, nullable=False)
    user_id: str = Field(foreign_key="users.user_id", nullable=False, index=True)
    mcp_server_id: uuid.UUID = Field(foreign_key="mcp_servers.mcp_server_id", nullable=False, index=True)
    # OAUTH_OBO fields
    access_token_enc: str | None = Field(default=None, sa_type=Text)
    refresh_token_enc: str | None = Field(default=None, sa_type=Text)
    token_type: str | None = Field(default=None, sa_type=Text)  # usually "Bearer"
    expires_at: datetime | None = Field(default=None, sa_column=Column(sa.DateTime(timezone=True), nullable=True))
    scopes: list[str] | None = Field(default=None, sa_column=Column(postgresql.ARRAY(Text), nullable=True))
    # M2M_PER_USER field
    api_key_enc: str | None = Field(default=None, sa_type=Text)
    # Lifecycle
    granted_at: datetime = Field(
        sa_column=Column(sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()"))
    )
    revoked_at: datetime | None = Field(default=None, sa_column=Column(sa.DateTime(timezone=True), nullable=True))
    last_used_at: datetime | None = Field(default=None, sa_column=Column(sa.DateTime(timezone=True), nullable=True))
    last_refresh_error: str | None = Field(default=None, sa_type=Text)

    __table_args__ = (
        # One active grant per (user, server).  Soft-revoked rows are
        # excluded so re-authorization stays cheap.
        sa.Index(
            "uq_mcp_user_grants_active",
            "user_id",
            "mcp_server_id",
            unique=True,
            postgresql_where=sa.text("revoked_at IS NULL"),
        ),
    )


class McpGrantEvent(SQLModel, table=True):
    """Append-only audit log for grant lifecycle + usage."""

    __tablename__ = "mcp_grant_events"

    event_id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True, nullable=False)
    user_id: str = Field(foreign_key="users.user_id", nullable=False, index=True)
    mcp_server_id: uuid.UUID = Field(foreign_key="mcp_servers.mcp_server_id", nullable=False, index=True)
    agent_session_id: uuid.UUID | None = Field(
        default=None,
        foreign_key="agent_sessions.agent_session_id",
        nullable=True,
    )
    event_type: McpGrantEventType = Field(
        sa_column=Column(sa_Enum(McpGrantEventType, name="mcp_grant_event_type"), nullable=False),
    )
    occurred_at: datetime = Field(
        sa_column=Column(sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()"))
    )
    meta: dict | None = Field(default=None, sa_column=Column(postgresql.JSONB, nullable=True))
