name: Lint and test

on:
  push:
    branches:
      - main
  pull_request:

# Required permissions for dorny/path-filter
permissions:
  contents: read
  packages: read
  pull-requests: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      has_python_changes: ${{ steps.filter.outputs.has_python_changes }}
      has_db_changes: ${{ steps.filter.outputs.has_db_changes }}
      has_dynamic_app_settings_changes: ${{ steps.filter.outputs.has_dynamic_app_settings_changes }}
      has_reward_rule_changes: ${{ steps.filter.outputs.has_reward_rule_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            has_python_changes:
              - '**/*.py'
              - 'pyproject.toml'
              - 'poetry.lock'
            has_db_changes:
              - 'ypl/db/**'
              - 'alembic.ini'
              - 'tests/conftest.py'
              - 'tests/test_db_datetime_timezone.py'
            has_dynamic_app_settings_changes:
              - 'data/dynamic_app_settings*.yml'
            has_reward_rule_changes:
              - 'data/reward_rules.yml'

  lint:
    needs: changes
    if: needs.changes.outputs.has_python_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-test-runner

      - name: Run lint
        run: |
          poetry run ruff check . --output-format=github
          poetry run ruff format . --check

  mypy:
    needs: changes
    if: needs.changes.outputs.has_python_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-test-runner

      - name: Cache mypy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-v2-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            mypy-v2-${{ hashFiles('pyproject.toml') }}-
            mypy-v2-

      - name: Run mypy
        run: poetry run mypy --config-file=pyproject.toml .

  test:
    needs: changes
    if: needs.changes.outputs.has_python_changes == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-test-runner

      - name: Create env file for tests
        run: cp .env.test .env

      - name: Run tests
        env:
          ENVIRONMENT: test
        run: poetry run pytest -m 'not alembic' --timeout=120

  test-alembic:
    needs: changes
    if: needs.changes.outputs.has_db_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-test-runner

      - name: Create env file for tests
        run: cp .env.test .env

      - name: Run alembic tests
        env:
          ENVIRONMENT: test
        run: poetry run pytest --test-alembic tests/conftest.py tests/alembic/test_db_datetime_timezone.py

  dynamic-app-settings:
    needs: changes
    if: needs.changes.outputs.has_dynamic_app_settings_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-test-runner

      - name: Run dynamic app settings tests
        run: poetry run pytest ypl/backend/tests/test_dynamic_app_settings.py

  reward-rules:
    needs: changes
    if: needs.changes.outputs.has_reward_rule_changes == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python environment
        uses: ./.github/actions/setup-test-runner

      - name: Run reward rules tests
        run: poetry run pytest ypl/backend/tests/test_rewards.py

  lint-and-test-backend:
    needs: [lint, mypy, test, test-alembic, dynamic-app-settings, reward-rules]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Successful deploy
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing deploy
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1